FROM node:18-alpine

WORKDIR /app

# Copiar package.json
COPY package*.json ./

# Instalar dependências
RUN npm install --production

# Copiar código
COPY . .

# Porta padrão do container
EXPOSE 80

# Variáveis de ambiente
ENV NODE_ENV=production
ENV PORT=80

# Start do servidor
CMD ["node", "server.js"]
